general:
  isTest: false
  description: |
    明治大学 宮下研究室 機関リポジトリ
  siteName: Miyashita Lab Research
  siteUrl: 'https://research.miyashita.com'
  twitterID: '@Miyashita_Lab'
  searchID: '006475268403292805769:ayfwuy8akxg'
